### ISSUE TITLE
README!

### ISSUE THREAD

**Issue by BunsenMcDubbs** [HackGT/Ultimate-Checkin#5]
READMEs are the best ❤️ . It makes the project shinier, friendlier, and more professional.

[relevant doc from HackMIT](https://github.com/HackMIT/open-source/blob/master/checklist.md)

**Comment by petschekr** [comment]
Added in 8e9a972. I still need to add a section describing the API but this should cover most things. It'll be in the `develop` branch until the next release.

**Comment by petschekr** [comment]
Landed in 85aacfb7d951e7ce309f8c86d140f9c3841a02ad with the v1.1.0 release
