### ISSUE TITLE
Improve performance for large lists

### ISSUE THREAD

**Issue by petschekr** [HackGT/Ultimate-Checkin#8]
Searching and loading large (~300 or more) lists of attendees causes a significant delay that is only made worse by the fact that the list is destroyed and recreated upon every keypress in the search field. [Relevant section of code](https://github.com/HackGT/Ultimate-Checkin/blob/master/client/js/main.ts#L136) that removes and recreates new DOM elements in an inefficient manner.

**Comment by BunsenMcDubbs** [comment]
Using a front-end framework might help with this (they normally have built-in support for long lists) but there is also probably a small library that can do this automagically... (or we can built it and eventually spin it out as a separate project! <3 open source cc @illegalprime )

**Comment by illegalprime** [comment]
@petschekr I hear react is pretty good at quickly destroying / recreating the DOM.
What do you think?

**Comment by Anish2** [comment]
@petschekr @illegalprime @BunsenMcDubbs I think we should use Clusterize.js (https://clusterize.js.org/). It has simple methods for our use case (append(), clear()). Also, if we simply want optimizations maybe try some of these (http://jquery-howto.blogspot.com/2009/02/5-easy-tips-on-how-to-improve-code.html).

**Comment by petschekr** [comment]
@illegalprime This section of code is just poorly optimized to get this app finished on time for HackGTeeny. A much more efficient way to do this would be to reuse the existing DOM elements rather than deleting them and recreating them on every keypress. I don't think adding another library like React is the optimal solution in this case.
